### ISSUE TITLE
Pebble with error

### ISSUE THREAD

**Issue by eniodefarias** [diversen/ppm-project-manager#2]
NT: 500 Internal Server Error
Message: Undefined array key "lifetime"
In: /var/www/public_html/ppm4/ppm-project-manager/vendor/diversen/pebble-framework/src/Session.php (19)
Trace: 
#0 /var/www/public_html/ppm4/ppm-project-manager/vendor/diversen/pebble-framework/src/Session.php(19): Pebble\App\CommonUtils->Pebble\App\{closure}()
#1 /var/www/public_html/ppm4/ppm-project-manager/vendor/diversen/pebble-framework/src/App/CommonUtils.php(70): Pebble\Session::setConfigSettings()
#2 /var/www/public_html/ppm4/ppm-project-manager/src/AppMain.php(33): Pebble\App\CommonUtils->sessionStart()
#3 /var/www/public_html/ppm4/ppm-project-manager/vendor/diversen/pebble-framework/src/App/AppExec.php(90): App\AppMain->run()
#4 /var/www/public_html/ppm4/ppm-project-manager/www/index.php(13): Pebble\App\AppExec->run()
#5 {main}

**Comment by diversen** [comment]
For some reason it seems like you are missing 'lifetime' in the config/Session.php file or in config-locale/Session.php 
You can see how it should look like here: https://github.com/diversen/ppm-project-manager/blob/main/config/Session.php

If you are using 'main' branch it seems to work fine. I did a test install.
